### ISSUE TITLE
Decidir a abordagem do projeto

### ISSUE THREAD

**Issue by marciofernandes12** [marciofernandes12/projectunifg#1]
Debater temas 
Brainstorm

**Comment by danilo-lima-developer** [comment]
Problema: A necessidade do distanciamento social em decorrência da pandemia do novo coronavírus causou graves problemas no setor educacional
Solução: Aplicação cuja finalidade é organizar encontros virtuais de estudo. No caso os estudantes realizarão um cadastro para selecionar as matérias e assuntos de seu interesse, com base nisso, o sistema listará outras pessoas com o mesmo objetivo, fornecendo salas de texto e vídeo e chat privado, para assim estabelecerem uma conexão, além de nutrirem suas bases de conhecimento.

**Comment by danielmiquiles** [comment]
Problema: A defasagem do ensino publico brasileiro.
Solução: Um portal direcionado ao publico de escolas publicas e de vunerabilidade social para sanar dúvidas com professores voluntários em aulas ao vivo a distancia.
